"""Golden-fixture tests for vectorized_feasibility.

Verifies that the new vectorized implementations of:
- build_proxy_portfolio
- compute_liquidity_coverage
- compute_tail_concentration
- compute_small_cap_concentration
- compute_signal_half_life
- compute_rebalance_stress

match the golden values computed by the legacy `research.feasibility.*`
modules (generated by `generate_golden.py`).
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest
import yaml

from research.compute.vectorized_feasibility import (
    build_proxy_portfolio,
    compute_liquid_flag,
    compute_liquidity_coverage,
    compute_rebalance_stress,
    compute_signal_autocorr_lag1,
    compute_signal_half_life,
    compute_small_cap_concentration,
    compute_small_cap_flag,
    compute_tail_concentration,
)

FIXTURES = Path(__file__).parent / "_fixtures"
INPUTS = FIXTURES / "inputs"
OUTPUTS = FIXTURES / "outputs"

ATOL = 1e-10


@pytest.fixture(scope="module")
def candidate_signal() -> pd.DataFrame:
    return pd.read_parquet(INPUTS / "candidate_signal.parquet")


@pytest.fixture(scope="module")
def tradable_mask() -> pd.DataFrame:
    return pd.read_parquet(INPUTS / "tradable_mask.parquet")


@pytest.fixture(scope="module")
def amount_data() -> pd.DataFrame:
    return pd.read_parquet(INPUTS / "amount_data.parquet")


@pytest.fixture(scope="module")
def market_cap() -> pd.DataFrame:
    return pd.read_parquet(INPUTS / "market_cap_data.parquet")


@pytest.fixture(scope="module")
def golden() -> dict:
    with open(OUTPUTS / "golden.yaml") as f:
        return yaml.safe_load(f)


@pytest.fixture(scope="module")
def proxy(
    candidate_signal: pd.DataFrame, tradable_mask: pd.DataFrame
):
    return build_proxy_portfolio(
        candidate_signal, tradable_mask, long_pct=0.2, short_pct=0.2
    )


class TestProxyPortfolio:
    def test_turnover_mean_matches_golden(
        self, proxy, golden: dict
    ) -> None:
        result = float(proxy.turnover.mean())
        assert result == pytest.approx(
            golden["feasibility"]["turnover_mean"], abs=ATOL
        )

    def test_weights_sum_to_zero_per_date(self, proxy) -> None:
        """Market-neutral: long weights = short weights in magnitude."""
        long_per_date = proxy.long_weights["weight"].groupby(level=0).sum()
        short_per_date = proxy.short_weights["weight"].groupby(level=0).sum()
        net = long_per_date + short_per_date
        # Each date should net to zero (up to floating point)
        assert (net.abs() < 1e-10).all()

    def test_abs_weights_equal_long_plus_short_magnitude(self, proxy) -> None:
        calculated = (
            proxy.long_weights["weight"].abs()
            + proxy.short_weights["weight"].abs()
        )
        pd.testing.assert_series_equal(
            proxy.abs_weights["weight"].sort_index(),
            calculated.sort_index(),
            check_names=False,
        )


class TestLiquidityCoverage:
    def test_matches_golden(
        self,
        proxy,
        amount_data: pd.DataFrame,
        golden: dict,
    ) -> None:
        liquid_flag = compute_liquid_flag(amount_data, window=20, pct=0.30)
        result = compute_liquidity_coverage(proxy.abs_weights, liquid_flag)
        assert result == pytest.approx(
            golden["feasibility"]["liquidity_coverage"], abs=1e-6
        )


class TestTailConcentration:
    def test_matches_golden(self, proxy, golden: dict) -> None:
        result = compute_tail_concentration(proxy.abs_weights, top_k=10)
        assert result == pytest.approx(
            golden["feasibility"]["tail_concentration"], abs=ATOL
        )


class TestSmallCapConcentration:
    def test_matches_golden(
        self, proxy, market_cap: pd.DataFrame, golden: dict
    ) -> None:
        small_cap_flag = compute_small_cap_flag(market_cap, pct=0.30)
        result = compute_small_cap_concentration(proxy.abs_weights, small_cap_flag)
        assert result == pytest.approx(
            golden["feasibility"]["small_cap_concentration"], abs=1e-6
        )


class TestSignalHalfLife:
    def test_matches_golden(
        self, candidate_signal: pd.DataFrame, golden: dict
    ) -> None:
        result = compute_signal_half_life(candidate_signal, max_lag=20)
        assert result == pytest.approx(
            golden["feasibility"]["half_life"], abs=ATOL
        )


class TestSignalAutocorrLag1:
    def test_returns_finite_for_autocorrelated_signal(
        self, candidate_signal: pd.DataFrame
    ) -> None:
        # The fixture signal is smooth enough to have non-trivial lag-1 corr
        result = compute_signal_autocorr_lag1(candidate_signal)
        assert result is not None
        assert -1.0 <= result <= 1.0

    def test_empty_signal_returns_none(self) -> None:
        empty = pd.DataFrame(
            columns=["value"],
            index=pd.MultiIndex.from_tuples([], names=["datetime", "instrument"]),
        )
        assert compute_signal_autocorr_lag1(empty) is None


class TestRebalanceStress:
    def test_matches_golden(self, golden: dict) -> None:
        g = golden["feasibility"]
        result = compute_rebalance_stress(
            g["turnover_mean"],
            g["tail_concentration"],
            g["liquidity_coverage"],
        )
        assert isinstance(result, float)
        assert result == pytest.approx(
            g["rebalance_stress"]["proxy"], abs=ATOL
        )
