"""Vectorized Barra residual IC — CP04 Risk Cleanness input.

Legacy ``research.risk.exposures.compute_barra_exposures`` runs a per-date
Python for-loop over ~600 trading days, each doing a separate
``np.linalg.lstsq`` on that date's valid stock subset. For a 1000-candidate
batch this is ~600,000 OLS calls, each ~1 ms → 10 minutes total just for
Barra, which dominates Phase 2 cost.

This module replaces the inner loop with a **3D-tensor pinv + einsum**
batch as required by refactor_plan §11:

* pivot factor & styles to shape ``(n_dates, n_symbols, n_styles+1)``
  where the ``+1`` is the OLS intercept column
* mask invalid (date, symbol) cells to zero in both X and y
* compute ``XtX`` and ``Xty`` via ``einsum``
* batch ``np.linalg.pinv`` once on the ``(n_dates, p, p)`` Gram tensor
* multiply ``XtX_inv @ Xty`` via ``einsum`` to get per-date ``beta``
* compute ``resid`` and ``R²`` entirely with broadcasting

The "per-date valid-stock set varies" difficulty is handled by zero-masking
rather than Python looping: OLS on a zero-masked row gives the same answer
as OLS on the unmasked subset because zero rows contribute nothing to the
Gram matrix or to the cross-term. Dates where the valid count falls below
``min_obs`` are dropped before aggregation so their zero-mean stats don't
pollute the averages.

Mathematical equivalence to the legacy path is verified in
``test_vectorized_barra.py`` — all outputs must match the golden fixture
(generated by the legacy loop) to 1e-6.
"""

from __future__ import annotations

from typing import Any

import numpy as np
import pandas as pd

from core.factor_stats import (
    daily_cross_sectional_ic,
    daily_cross_sectional_ic_from_wides,
    ic_summary,
)

# Fixed Barra style order — must match what the style_matrix carries
STYLE_NAMES: list[str] = [
    "log_circ_cap",
    "book_to_price",
    "mom_12_1",
    "str_1m",
    "vol_20d",
    "turnover_20d",
    "ep_ratio",
]

# Crowding classification thresholds
CROWDING_R2_HIGH = 0.25
CROWDING_R2_MEDIUM = 0.10
CROWDING_EXPOSURE_HIGH = 0.5
CROWDING_EXPOSURE_MEDIUM = 0.3

# Below this absolute raw IC, survival ratio is not meaningful
SURVIVAL_RAW_IC_MIN = 1e-4


def _empty_result() -> dict[str, Any]:
    return {
        "style_exposures": {},
        "style_r_squared": None,
        "barra_residual_ic": None,
        "barra_residual_icir": None,
        "alpha_survival_ratio": None,
        "dominant_style_exposure": None,
        "style_crowding_risk": "low",
        "style_contributions": [],
    }


def _leave_one_out_residual_ic(
    X_styles: np.ndarray,
    y: np.ndarray,
    valid: np.ndarray,
    common_dates: pd.DatetimeIndex,
    symbols: pd.Index,
    date_ok: np.ndarray,
    forward_returns_wide: pd.DataFrame,
    skip_idx: int,
) -> float | None:
    """OLS on styles minus column ``skip_idx``, return residual IC mean.

    The regression builds X' = [intercept, styles except skip_idx] and runs
    the same batched pinv pipeline as the full Barra regression. The IC
    is computed via :func:`daily_cross_sectional_ic_from_wides` directly
    on the residual wide (no stack → flat → merge → re-pivot detour),
    which is the dominant cost when this is called 7× per candidate.
    Returns None if the residual is empty / IC undefined.
    """
    n_dates, n_symbols = y.shape
    other_styles = np.delete(X_styles, skip_idx, axis=-1)
    X_k = np.concatenate(
        [np.ones((n_dates, n_symbols, 1), dtype=other_styles.dtype), other_styles],
        axis=-1,
    )
    y_masked = np.where(valid, y, 0.0)
    X_k_masked = np.where(valid[..., None], X_k, 0.0)
    XtX_k = np.einsum("dsp,dsq->dpq", X_k_masked, X_k_masked)
    Xty_k = np.einsum("dsp,ds->dp", X_k_masked, y_masked)
    beta_k = np.einsum("dpq,dq->dp", np.linalg.pinv(XtX_k), Xty_k)
    yhat_k = np.einsum("dsp,dp->ds", X_k_masked, beta_k)
    resid_k = np.where(valid, y - yhat_k, 0.0)

    valid_ok = valid[date_ok]
    residual_wide = pd.DataFrame(
        resid_k[date_ok],
        index=common_dates[date_ok],
        columns=symbols,
    ).where(valid_ok)
    if residual_wide.dropna(how="all").empty:
        return None
    ic_series = daily_cross_sectional_ic_from_wides(residual_wide, forward_returns_wide)
    if ic_series.empty:
        return None
    return ic_summary(ic_series).get("ic_mean")


def _build_style_contributions(
    X_styles: np.ndarray,
    y: np.ndarray,
    valid: np.ndarray,
    common_dates: pd.DatetimeIndex,
    symbols: pd.Index,
    date_ok: np.ndarray,
    forward_returns_wide: pd.DataFrame,
    style_cols: list[str],
    raw_view_ic: float | None,
    barra_residual_ic: float | None,
) -> list[dict]:
    """Per-style alpha attribution via leave-one-out Barra regression.

    For each style k, runs OLS with all styles EXCEPT k, measures residual
    IC, and reports how much IC **would have been retained** if k weren't
    in the control set. The difference ``|ic_without_k| - |barra_residual_ic|``
    estimates style k's contribution to stripping alpha in the full regression.

    Sorted by ``|delta_ic|`` descending so the top row is the dominant killer.
    Returns list of dicts, empty if full residual IC undefined.
    """
    if (
        barra_residual_ic is None
        or not np.isfinite(barra_residual_ic)
        or raw_view_ic is None
    ):
        return []

    total_gap = abs(raw_view_ic) - abs(barra_residual_ic)
    contributions: list[dict] = []
    for k, name in enumerate(style_cols):
        ic_without = _leave_one_out_residual_ic(
            X_styles, y, valid, common_dates, symbols, date_ok,
            forward_returns_wide, skip_idx=k,
        )
        if ic_without is None or not np.isfinite(ic_without):
            contributions.append({
                "style": name, "delta_ic": None, "ic_without": None, "pct": None,
            })
            continue
        delta_ic = abs(ic_without) - abs(barra_residual_ic)
        pct = round(100 * delta_ic / total_gap, 1) if total_gap > 1e-9 else None
        contributions.append({
            "style": name,
            "delta_ic": _safe_round(delta_ic),
            "ic_without": _safe_round(ic_without),
            "pct": pct,
        })

    contributions.sort(
        key=lambda c: abs(c["delta_ic"]) if c["delta_ic"] is not None else 0.0,
        reverse=True,
    )
    return contributions


def _classify_crowding(r2: float, exposures: dict[str, float]) -> str:
    max_exp = max(exposures.values()) if exposures else 0.0
    any_above_medium = any(v > CROWDING_EXPOSURE_MEDIUM for v in exposures.values())

    if r2 > CROWDING_R2_HIGH and max_exp > CROWDING_EXPOSURE_HIGH:
        return "high"
    if r2 > CROWDING_R2_MEDIUM or any_above_medium:
        return "medium"
    return "low"


def _safe_round(v: float | None, decimals: int = 6) -> float | None:
    if v is None or not np.isfinite(v):
        return None
    return round(float(v), decimals)


def compute_barra_exposures(
    factor_flat: pd.DataFrame,
    style_matrix: pd.DataFrame,
    forward_returns_flat: pd.DataFrame,
    raw_view_ic: float,
    min_obs: int = 50,
    *,
    style_wides: dict[str, pd.DataFrame] | None = None,
    forward_returns_wide: pd.DataFrame | None = None,
) -> dict[str, Any]:
    """Batched Barra OLS + residual IC + crowding classification.

    Parameters
    ----------
    factor_flat
        Flat ``[time, symbol, value]`` frame — the already-preprocessed
        signal whose alpha we want to measure net of style.
    style_matrix
        MultiIndex (datetime, instrument) DataFrame with the 7 ``STYLE_NAMES``
        columns, already normalized.
    forward_returns_flat
        Flat ``[time, symbol, value]`` frame of forward returns for the
        residual IC computation.
    raw_view_ic
        Pre-computed raw IC of the factor (before style removal), used to
        compute ``alpha_survival_ratio = |residual_ic| / |raw_ic|``.
    min_obs
        Per-date minimum valid stock count. Dates below this drop from
        the aggregation.

    Returns
    -------
    dict
        ``style_exposures`` (dict of name→mean|beta|),
        ``style_r_squared`` (median across dates),
        ``barra_residual_ic``, ``barra_residual_icir``,
        ``alpha_survival_ratio``, ``dominant_style_exposure``,
        ``style_crowding_risk``.
    """
    if factor_flat.empty or style_matrix.empty:
        return _empty_result()

    style_cols = [c for c in STYLE_NAMES if c in style_matrix.columns]
    if not style_cols:
        return _empty_result()

    # ----- 1. Pivot to wide (date × symbol) aligned frames -----
    fv_wide = factor_flat.pivot(index="time", columns="symbol", values="value")
    fv_wide.index = pd.DatetimeIndex(fv_wide.index)

    # Align dates: intersect factor dates with style dates
    style_dates = style_matrix.index.get_level_values(0).unique()
    common_dates = fv_wide.index.intersection(style_dates)
    if len(common_dates) == 0:
        return _empty_result()
    fv_wide = fv_wide.loc[common_dates]

    # Build the (n_dates, n_symbols, n_styles) style tensor by pivoting
    # each style column, aligning to fv_wide's symbol axis. ``style_wides``
    # may be passed in pre-pivoted (Phase 2 caches it once per batch);
    # otherwise we pivot here.
    symbols = fv_wide.columns
    if style_wides is None:
        style_wides = {col: style_matrix[col].unstack(level=-1) for col in style_cols}
    style_tensors = []
    for col in style_cols:
        s_wide = style_wides[col]
        if not isinstance(s_wide.index, pd.DatetimeIndex):
            s_wide = s_wide.copy()
            s_wide.index = pd.DatetimeIndex(s_wide.index)
        # Align to fv_wide index and columns (inserts NaN for missing)
        s_wide = s_wide.reindex(index=common_dates, columns=symbols)
        style_tensors.append(s_wide.to_numpy())

    # X_styles: (n_dates, n_symbols, n_styles)
    X_styles = np.stack(style_tensors, axis=-1)
    y = fv_wide.to_numpy()  # (n_dates, n_symbols)

    # Add intercept column → (n_dates, n_symbols, n_params=1+n_styles)
    n_dates, n_symbols = y.shape
    n_params = X_styles.shape[-1] + 1
    X = np.concatenate(
        [np.ones((n_dates, n_symbols, 1), dtype=X_styles.dtype), X_styles],
        axis=-1,
    )

    # ----- 2. Build per-cell validity mask -----
    # A cell is valid if y is finite AND all style columns are finite.
    y_valid = np.isfinite(y)
    x_valid = np.all(np.isfinite(X_styles), axis=-1)
    valid = y_valid & x_valid  # (n_dates, n_symbols)
    n_valid_per_date = valid.sum(axis=1)  # (n_dates,)

    # Zero-mask y and X at invalid cells so they contribute nothing to
    # XtX and Xty. Keep original non-finite values out of the math.
    y_masked = np.where(valid, y, 0.0)  # (n_dates, n_symbols)
    X_masked = np.where(valid[..., None], X, 0.0)  # (n_dates, n_symbols, n_params)

    # ----- 3. Batched OLS via pinv + einsum -----
    # XtX[d] = sum_s X_masked[d,s,:].T @ X_masked[d,s,:]
    # einsum: 'dsp,dsq -> dpq'
    XtX = np.einsum("dsp,dsq->dpq", X_masked, X_masked)  # (n_dates, p, p)
    # Xty[d] = sum_s X_masked[d,s,:] * y_masked[d,s]
    # einsum: 'dsp,ds -> dp'
    Xty = np.einsum("dsp,ds->dp", X_masked, y_masked)  # (n_dates, p)

    # Batched pseudo-inverse — np.linalg.pinv is native 3D aware
    XtX_inv = np.linalg.pinv(XtX)  # (n_dates, p, p)

    # beta[d] = XtX_inv[d] @ Xty[d]
    # einsum: 'dpq,dq -> dp'
    beta = np.einsum("dpq,dq->dp", XtX_inv, Xty)  # (n_dates, p)

    # ----- 4. Residuals + R² per date -----
    # yhat[d, s] = X[d, s, :] @ beta[d, :]
    # Use the ORIGINAL X (with NaN for invalid cells → they get dropped below)
    yhat = np.einsum("dsp,dp->ds", X_masked, beta)  # (n_dates, n_symbols)
    # Residual only defined at valid cells; zero elsewhere so sums ignore them
    resid = np.where(valid, y - yhat, 0.0)

    # Per-date means over valid subset
    sum_y_valid = y_masked.sum(axis=1)
    mean_y = np.where(
        n_valid_per_date > 0,
        sum_y_valid / np.maximum(n_valid_per_date, 1),
        0.0,
    )  # (n_dates,)

    # ss_tot = sum((y - mean_y)^2 * valid) per date
    y_centered = np.where(valid, y - mean_y[:, None], 0.0)
    ss_tot = np.einsum("ds,ds->d", y_centered, y_centered)  # (n_dates,)
    ss_res = np.einsum("ds,ds->d", resid, resid)  # (n_dates,)

    r2 = np.where(ss_tot > 1e-12, 1.0 - ss_res / ss_tot, 0.0)
    r2 = np.clip(r2, 0.0, 1.0)

    # ----- 5. Drop dates with insufficient valid stocks -----
    date_ok = n_valid_per_date >= min_obs
    if not date_ok.any():
        return _empty_result()

    beta_ok = beta[date_ok]  # (n_ok, p)
    r2_ok = r2[date_ok]
    residual_wide_ok = pd.DataFrame(
        resid[date_ok],
        index=common_dates[date_ok],
        columns=symbols,
    )
    # Mask positions that were invalid → NaN (not zero) so they drop from
    # the residual IC computation
    valid_ok = valid[date_ok]
    residual_wide_ok = residual_wide_ok.where(valid_ok)

    # ----- 6. Aggregate style_exposures and R² -----
    # beta is [intercept, style_0, ..., style_{n-1}] — drop intercept.
    style_beta = beta_ok[:, 1:]  # (n_ok, n_styles)
    style_exposures = {
        name: float(np.mean(np.abs(style_beta[:, i])))
        for i, name in enumerate(style_cols)
    }
    style_r_squared = float(np.median(r2_ok))

    dominant_idx = int(
        np.argmax([style_exposures[n] for n in style_cols])
    )
    dominant_style = style_cols[dominant_idx]
    style_crowding_risk = _classify_crowding(style_r_squared, style_exposures)

    # ----- 7. Residual IC via wides path (skips residual flat round-trip) -----
    # Pivot returns once here for both the main residual IC + the LOO loop;
    # if the caller passed in a cached wide (Phase 2 batch), reuse it.
    if forward_returns_wide is None:
        forward_returns_wide = (
            forward_returns_flat
            .set_index(["time", "symbol"])["value"]
            .unstack(level=-1)
        )
    if residual_wide_ok.dropna(how="all").empty:
        barra_residual_ic = None
        barra_residual_icir = None
    else:
        residual_ic_series = daily_cross_sectional_ic_from_wides(
            residual_wide_ok, forward_returns_wide
        )
        if residual_ic_series.empty:
            barra_residual_ic = None
            barra_residual_icir = None
        else:
            ic_stats = ic_summary(residual_ic_series)
            barra_residual_ic = ic_stats.get("ic_mean")
            barra_residual_icir = ic_stats.get("ic_ir")

    # ----- 8. Alpha survival ratio -----
    if (
        raw_view_ic is None
        or not np.isfinite(raw_view_ic)
        or abs(raw_view_ic) < SURVIVAL_RAW_IC_MIN
    ):
        alpha_survival: float | None = None
    elif barra_residual_ic is not None and np.isfinite(barra_residual_ic):
        alpha_survival = abs(barra_residual_ic) / abs(raw_view_ic)
    else:
        alpha_survival = None

    # ----- 9. Per-style leave-one-out attribution -----
    style_contributions = _build_style_contributions(
        X_styles=X_styles,
        y=y,
        valid=valid,
        common_dates=common_dates,
        symbols=symbols,
        date_ok=date_ok,
        forward_returns_wide=forward_returns_wide,
        style_cols=style_cols,
        raw_view_ic=raw_view_ic,
        barra_residual_ic=barra_residual_ic,
    )

    return {
        "style_exposures": style_exposures,
        "style_r_squared": style_r_squared,
        "barra_residual_ic": _safe_round(barra_residual_ic),
        "barra_residual_icir": _safe_round(barra_residual_icir),
        "alpha_survival_ratio": _safe_round(alpha_survival, 4),
        "dominant_style_exposure": dominant_style,
        "style_crowding_risk": style_crowding_risk,
        "style_contributions": style_contributions,
    }
